[theme]
# Base theme
base = "light"

# Core Colors
primaryColor = "#d8ac8c"
backgroundColor = "#FBF6F2"
secondaryBackgroundColor = "#f2e3d9"
textColor = "#1A1A1A"
linkColor = "#000000"
codeBackgroundColor = "#F5F5F5"

# Typography
font = "serif"
codeFont = "monospace"
codeFontSize = "0.875rem"
headingFont = "serif"
baseFontSize = 17

# Layout & Borders
baseRadius = "none"
buttonRadius = "5%"
borderColor = "#CCCCCC"
dataframeBorderColor = "#BBBBBB"
showWidgetBorder = true
showSidebarBorder = true


[theme.sidebar]
primaryColor = "#000000"
backgroundColor = "#f2e3d9"
secondaryBackgroundColor = "#eedacc"
textColor = "#333333"
linkColor = "#000000"
codeBackgroundColor = "#EEEEEE"
font = "serif"
codeFont = "monospace"
codeFontSize = "0.8rem"
headingFont = "serif"
baseRadius = "none"
buttonRadius = "5%"
borderColor = "#CCCCCC"
dataframeBorderColor = "#BBBBBB"
showWidgetBorder = true